spring:
  application:
    name: poc-graph
  main:
    banner-mode: console
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  cassandra:
    local-datacenter: datacenter1
management:
  endpoints:
    web:
      exposure:
        include: 'health,metrics,prometheus'
  endpoint:
    health:
      access: READ_ONLY
      probes:
        enabled: true
      show-details: always
    metrics:
      access: READ_ONLY
    prometheus:
      access: READ_ONLY
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
    defaults:
      enabled: true
logging:
  file:
    path: .
app:
  janusgraph:
    config:
      contact_point: localhost
      contact_port: 8182
