spring:
  application:
    name: poc-graph
  main:
    banner-mode: console
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  cassandra:
    local-datacenter: datacenter1
management:
  endpoints:
    web:
      exposure:
        include: 'health,metrics,prometheus'
  endpoint:
    health:
      access: READ_ONLY
      probes:
        enabled: true
      show-details: always
    metrics:
      access: READ_ONLY
    prometheus:
      access: READ_ONLY
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
    defaults:
      enabled: true
logging:
  file:
    path: .
app:
  janusgraph:
    config:
      gremlin_graph: org.janusgraph.core.JanusGraphFactory
      storage_backend: cql
      storage_hostname: localhost
      storage_cql_keyspace: jgex
      storage.cql.local-datacenter: datacenter1
      basic.load-balancing-policy.local-datacenter: datacenter1
      index_jgex_backend: elasticsearch
      index_jgex_index-name: jgex
      index_jgex_hostname: localhost
      cluster_url: localhost
      cluster_port: 8182
