graph = JanusGraphFactory.open('cql:cassandra')
mgmt = graph.openManagement()
mgmt.makeEdgeLabel("father").make()
mgmt.makeEdgeLabel("mother").make()
mgmt.makeEdgeLabel("married").make()
mgmt.makePropertyKey("shortName").dataType(String.class).cardinality(Cardinality.SINGLE).make()
mgmt.makePropertyKey("name").dataType(String.class).cardinality(Cardinality.SINGLE).make()
mgmt.makePropertyKey("category").dataType(String.class).cardinality(Cardinality.SINGLE).make()
mgmt.makePropertyKey("description").dataType(String.class).cardinality(Cardinality.SINGLE).make()
mgmt.makePropertyKey("gender").dataType(String.class).cardinality(Cardinality.SINGLE).make()
mgmt.buildIndex("byShortName", Vertex.class).addKey(mgmt.getPropertyKey("shortName")).buildCompositeIndex()
mgmt.buildIndex("byName", Vertex.class).addKey(mgmt.getPropertyKey("name")).buildCompositeIndex()
mgmt.buildIndex("byCategory", Vertex.class).addKey(mgmt.getPropertyKey("category")).buildCompositeIndex()