services:
  janusgraph:
    image: janusgraph/janusgraph:latest
    container_name: jce-janusgraph
    environment:
      JANUS_PROPS_TEMPLATE: cql-es
      janusgraph.storage.hostname: jce-cassandra
      janusgraph.index.search.hostname: jce-elastic
    ports:
      - "8182:8182"
    networks:
      - jce-network
    healthcheck:
      test: ["CMD", "bin/gremlin.sh", "-e", "scripts/remote-connect.groovy"]
      interval: 10s
      timeout: 30s
      retries: 3
  cassandra:
    image: cassandra:4.0.17
    container_name: jce-cassandra
    ports:
      - "9042:9042" # Cassandra CQL port
      - "9160:9160"
    volumes:
      - "./cassandra_data:/var/lib/cassandra"
    healthcheck:
      test: [ "CMD", "nodetool", "status" ]
      interval: 30s
      retries: 5
      timeout: 10s
    networks:
      - jce-network
  elasticsearch:
    image: elasticsearch:8.17.1
    container_name: jce-elastic
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.host=0.0.0.0"
      - "network.host=0.0.0.0"
      - "transport.host=127.0.0.1"
      - "cluster.name=docker-cluster"
      - "xpack.security.enabled=false"
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
    networks:
      - jce-network
  janusgraph-visualizer:
    image: janusgraph/janusgraph-visualizer:latest
    container_name: jce-visualizer
    ports:
      - "3000:3000"
      - "3001:3001"
    networks:
      - jce-network
    depends_on:
      - janusgraph
    environment:
      - GRAPH_URL=http://jce-janusgraph:8182
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3001" ]
      interval: 10s
      retries: 3
networks:
  jce-network:
volumes:
  janusgraph-default-data: